name: Hugo Deploy

on:
  push:
    branches:
      - main  # 或者你的主分支名称
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Hugo PaperMod Deploy
      uses: Protomyst/Hugo-PaperMod-Deploy@1.0.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # 可选配置：
        # hugo_version: 'latest'          # Hugo 版本号，默认为最新版
